GET http://localhost:3000/
Accept: application/text
Accept-Language: fr


###
GET http://localhost:3000/users?lastname=Doe&page=2&items_per_page=1

###
GET http://localhost:3000/users/1


###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jane@t.fr",
  "password": "123456",
  "firstname": "Jane",
  "lastname": "Doe"
}